### ISSUE TITLE
two instances of reacts are being used

### ISSUE THREAD

**Issue by zsolt-dev** [EddiG/ssr-cra-graphql#1]
Hi,

This boilerplate looks promising but there are two instances of reacts.

One in root and one in client.

Would it be possible to include them from the same place?

**Comment by EddiG** [comment]
Thanks, @joesanta555 for the good point 👍 
I was away from this project, but I glad that you find it useful. I have thought about your suggestion and I agree it should be simpler to manage dependencies from one place, so I will merge the `client` project to the root project.

**Comment by EddiG** [comment]
@joesanta555 I would be thankful if you would try the #2 PR and share your thoughts.
