### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kjpopov** [EddiG/ssr-cra-graphql#3]
Add licence please, preferably Apache 2.0

**Comment by EddiG** [comment]
Could you explain your preference over MIT license? I thought to add that one.

**Comment by kjpopov** [comment]
MIT is even better thank you, some MRs may follow, we are going to upgrade the project a bit to use latest versions of apollo, react, babel, webpack etc... and use it as an initial scaffold setup to base other projects on it.

**Comment by EddiG** [comment]
Done
